stages:
  - build
  - test
  - Docker


build:
  stage: build

  tags:
    - all

  before_script:
    - echo $Env:Path;

  script:
    - mvn clean install -X -DskipTests


maven_test:
  stage: test

  tags:
    - all

  before_script:
    - echo $Env:Path
    - mvn clean install -DskipTests

  script:
    - mvn test -X


Docker_building:
  stage: Docker

  tags:
    - docker

  variables:
    DOCKER_IMAGE_NAME: "<username>/semester-3-2023-fontys"
    DOCKER_REGISTRY: "docker.io"

  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"

  script:
    - docker build -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    
  only:
    - main
