image: maven:3.8.4-openjdk-17

stages:
  - Docker
  - build
  - test

build:
  stage: build
  script:
    - mvn clean install


maven_test:
  stage: test

  before_script:
        - mvn clean install -DskipTests

  script:
    - mvn test -Dspring.profiles.active=test


Docker_building:
  stage: Docker

  image: docker:24.0.7

  services:
    - docker:24.0.7-dind

  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

  script:
    - docker build -t back-end .
