stages:
  - build
  - test
  - Docker


build:
  stage: build

  tags:
    - all

  before_script:
    - echo $Env:Path;

  script:
    - mvn clean install -X -DskipTests


maven_test:
  stage: test

  tags:
    - all

  before_script:
    - echo $Env:Path
    - mvn clean install -DskipTests

  script:
    - mvn test -X


Docker_building:
  stage: Docker

  tags:
    - docker

  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKERHUB_TOKEN $CI_REGISTRY

  script:
    - docker build -t back-end .
  only:
    - main
