stages:
  - build
  - test
  - Docker

variables:
  CI_BUILD_PATH: "C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.1.12-hotspot\\bin;C:\\Program Files\\Apache\\maven\\apache-maven-3.8.8\\bin"


build:
  stage: build

  tags:
    - all

  before_script:
    - echo $Env:Path;
    - $Env:Path += ";$CI_BUILD_PATH"
    - echo $Env:Path;

  script:
    - mvn clean install -X -DskipTests


maven_test:
  stage: test

  tags:
    - all

  before_script:
    - echo $Env:Path
    - $Env:Path += ";$CI_BUILD_PATH"
    - echo $Env:Path
    - mvn clean install -DskipTests

  script:
    - mvn test -X


Docker_building:
  stage: Docker

  tags:
    - docker

  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKERHUB_TOKEN $CI_REGISTRY

  script:
    - docker build -t back-end .
  only:
    - main
