image: maven:3.8.4-openjdk-17

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn clean install


maven_test:
  stage: test

  before_script:
        - mvn clean install -DskipTests

  script:
    - mvn test -Dspring.profiles.active=test


Docker_building:
  stage: deploy

  image: docker:19.03.12

  services:
  - docker:19.03.13-dind

  script:
   script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
