image: maven:3.8.4-openjdk-17

stages:
  - build
  - test
  - Docker

build:
  stage: build

  tags:
    - all
    
  script:
    - mvn clean install


maven_test:
  stage: test

  tags:
    - all

  before_script:
        - mvn clean install -DskipTests

  script:
    - mvn test -Dspring.profiles.active=test


Docker_building:
  stage: Docker

  image: docker:20.10.24

  tags:
    - docker

  services:
    - docker:20.10.24-dind

  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

  before_script:
    - docker login -i

  script:
    - docker build -t back-end .
