image: maven:3.8.4-openjdk-17

stages:
  - build
  - test
  - Docker

variables:
  CI_BUILD_PATH: "C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.1.12-hotspot\\bin;C:\\Program Files\\Apache\\maven\\apache-maven-3.8.8\\bin"


build:
  stage: build

  tags:
    - all

  before_script:
    - if [ -n "$DOCKER_HOST" ]; then
        echo "Running in a Docker container.";
      else
        echo $Env:Path;
        $Env:Path += ";$CI_BUILD_PATH"
        echo $Env:Path;
      fi

  script:
    - mvn clean install


maven_test:
  stage: test

  tags:
    - all

  before_script:

    - if [ -n "$DOCKER_HOST" ]; then
        echo "Running in a Docker container.";
      else
        echo $Env:Path;
        $Env:Path += ";$CI_BUILD_PATH"
        echo $Env:Path;
      fi
    - mvn clean install -DskipTests

  script:
    - mvn test


Docker_building:
  stage: Docker

  image: docker:20.10.24

  tags:
    - docker

  script:
    - docker build -t back-end .
