image: maven:3.8.4-openjdk-17

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn clean install


maven_test:
  stage: test

  before_script:
        - mvn clean install -DskipTests

  script:
    - mvn test -Dspring.profiles.active=test


Docker_building:
  stage: deploy
  image: maven:docker:19.03.12

  before_script:
    - apt-get update -y
    - apt-get install -y docker.io  # Install Docker
    - service docker start  # Start Docker service

  script:
    - docker build -t registry.gitlab.com/I517297/semester-3-back-end/DockerImages/dnd-scharacter-backend:latest .
    - docker push registry.gitlab.com/I517297/semester-3-back-end/DockerImages/dnd-scharacter-backend:latest
