image: maven:3.8.4-openjdk-17

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./mvnw package -DskipTests

test:
  stage: test
  script:
    - ./mvnw test -Dspring.profiles.active=test


